#file name depends   clusterGroupName in values-global.yaml --  namespaces > subscriptions > applications >

clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
    - open-cluster-management: #for ACM
        operatorGroup: true
    - openshift-nmstate: #for NMstate
        operatorGroup: true
    - openshift-local-storage: #for LSO
        operatorGroup: true
    - openshift-storage: #for ODF
        operatorGroup: true
    - openshift-cnv: #for CNF
        operatorGroup: true
    - quay-enterprise: #for quay
        operatorGroup: true
    #- policies
    - kafka-cluster: #for Kafka
        operatorGroup: true
    - openshift-logging:
        labels:
          openshift.io/cluster-monitoring: "true"
          argocd.argoproj.io/managed-by: "mgmt-gitops-hub"
        operatorGroup: true
        targetNamespaces:
    - openshift-operators-redhat:
        operatorGroup: true
    # STF Namespaces
    - service-telemetry:
        operatorGroup: true

    - cert-manager-operator:
        operatorGroup: true
    # End of STF related namespaces
    - prom-kafka-adapter: #for prometheus adapter
        operatorGroup: true
    - mgmt-apps: #for applications
        operatorGroup: true
    - ansible: #for ansible
        operatorGroup: true
    - rhacs-operator: #ACS
        operatorGroup: true
        targetNamespaces:
    - stackrox: #ACS_Central
        operatorGroup: true
    - openshift-update-service:
        operatorGroup: true

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.12

    nmstate:
      name: kubernetes-nmstate-operator
      namespace: openshift-nmstate
      channel: stable
      csv: kubernetes-nmstate-operator.4.16.0-202409111235

    lso:
      name: local-storage-operator
      namespace: openshift-local-storage
      channel: stable
      csv: local-storage-operator.v4.16.0-202410242205

    odf:
      name: odf-operator
      namespace: openshift-storage
      channel: stable-4.16
      csv: odf-operator.v4.16.13-rhodf

        #    cnv:
        #      name: kubevirt-hyperconverged
        #      namespace: openshift-cnv
        #      channel: stable
        #      csv: kubevirt-hyperconverged-operator.v4.14.4

      #    quay:
      #      name: quay-operator
      #      namespace: quay-enterprise
      #      channel: stable-3.11
      #      csv:
      #        quay-operator.v3.11.0

     
     # STF Operator
        #
    cluster-observability-operator:
      name: cluster-observability-operator
      namespace: openshift-operators
      channel: development

      #    openshift-cert-manager:
      #      name: openshift-cert-manager-operator
      #      namespace: cert-manager-operator
      #      channel: stable-v1

    service-telemetry:
      name: service-telemetry-operator
      namespace: service-telemetry
      channel: stable-1.5

    grafana:
      name: grafana-operator
      namespace: service-telemetry
      channel: v5
      source: community-operators



        #
        # End STF operators
        #
        #    kafka:
        #      name: amq-streams
        #      namespace: kafka-cluster
        #      channel: stable
        #      csv: amqstreams.v2.6.0-1

      #    logging:
      #      namespace: openshift-logging
      #      name: cluster-logging
      #      channel: stable-5.9
      #      source: redhat-operators
      #      csv: cluster-logging.v5.9.0

    talm:
      name: topology-aware-lifecycle-manager
      namespace: openshift-operators
      channel: stable

      #    ansible:
      #      name: ansible-automation-platform-operator
      #      namespace: ansible
      #      source: redhat-operators
      #      channel: stable-2.4

      # rhacs-operator:
      #      name: rhacs-operator
      #      namespace: rhacs-operator
      #      source: redhat-operators
      #      channel: stable

      #    osus:
      #      name: cincinnati-operator
      #      namespace: openshift-update-service
      #      source: redhat-operators
      #      channel: v1

  projects:
    - hub

  applications:
          #    perf-profile:
          #      name: perf-profile
          #      project: hub
          #      path: charts/mgt-hub/perf-profile

    acm:
      name: acm
      namespace: open-cluster-management
      project: hub
      path: charts/mgt-hub/acm
      ignoreDifferences:
        - group: internal.open-cluster-management.io
          kind: ManagedClusterInfo
          jsonPointers:
            - /spec/loggingCA
              
    acm-observability:
      name: acm-observability
      namespace: open-cluster-management-observability
      project: hub
      path: charts/mgt-hub/acm-observability


      #drtest:
      #name: drtest
      #namespace: open-cluster-management-backup
      #project: hub
      #path: charts/mgt-hub/drtest

    mce:
      name: mce
      namespace: multicluster-engine
      project: hub
      path: charts/mgt-hub/mce

    nmstate:
      name: nmstate-crd
      namespace: openshift-nmstate
      path: charts/mgt-hub/nmstate
      project: hub

        #    cnv:
        #      name: kubevirt-hyperconverged
        #      namespace: openshift-cnv
        #      path: charts/mgt-hub/cnv
        #      project: hub

    odf:
      name: odf
      namespace: openshift-storage
      path: charts/mgt-hub/openshift-data-foundations
      project: hub

    lso:
      name: local-storage
      namespace: openshift-local-storage
      path: charts/mgt-hub/lso
      project: hub

      #quay:
      #      name: quay
      #namespace: quay-enterprise
      #path: charts/mgt-hub/quay
      #project: hub

      #    kafka:
      #      name: kafka
      #      namespace: kafka-cluster
      #      path: charts/mgt-hub/kafka
      #      project: hub

      #    monitoring:
      #      name: monitoring
      #      namespace: prom-kafka-adapter
      #      path: charts/mgt-hub/monitoring
      #      project: hub

    gitops:
      name: gitops
      namespace: npss-gitops
      path: charts/mgt-hub/gitops
      project: hub

      #    logging:
      #      name: logging
      #      namespace: openshift-logging
      #      path: charts/mgt-hub/logging
      #      project: hub

    stf:
      name: stf
      namespace: service-telemetry
      path: charts/mgt-hub/stf
      project: hub

      #    vms:
      #      name: vms
      #      namespace: mgmt-apps
      #      project: hub
      #      path: charts/mgt-hub/vm-on-bm

      #    ansible:
      #      name: ansible
      #      path: charts/mgt-hub/ansible
      #      project: hub

      #    security:
      #      name: security
      #      namespace: stackrox
      #      path: charts/mgt-hub/rhacs-central
      #      project: hub

mgmt:
  provisioner_ip: 192.168.62.251 
  cluster_name: umrtestrocp
  domain: tim.tr
  dns_server_ip: 192.168.63.163,8.8.8.8
  apps_ns: mgmt-apps
  apps_nad_name: nad-br-apps
  apps_subnet: 192.168.63.0
  apps_subnet_len: 24
  apps_subnet_gw: 192.168.63.1
  #
  # Variables for Ansible playbooks
  #
  vars_path: /root/captivemgmtcluster/playbooks/vars
  deploy_idm: false
  deploy_satellite: false
  deploy_gitlab: false

  idm:
    qcow: rhel-9.2-x86_64-kvm.qcow2
    app_name: idm-server
    domain: identity
    password: redhat
    user: admin
    ip: 10.0.42.5
    hostname: idm1mgmt1
    ipaserver: idm1mgmt1.umrtestrocp.tim.tr

  satellite:
    qcow: rhel-8.8-x86_64-kvm.qcow2
    app_name: sat-server
    domain: satellite
    password: redhat
    user: admin
    ip: 10.0.42.4
    hostname: satellite

  git:
    qcow: rhel-9.2-x86_64-kvm.qcow2
    app_name: git-server
    domain: git
    password: redhat
    user: admin
    ip: 10.0.42.6
    hostname: git
    git_fqdn: git.umrtestrocp.tim.tr

  quay:
    namespace: quay-enterprise
    local: quay1.apps.umrtestrocp.tim.tr
    remote: quay2.apps.umrtestrocp.tim.tr
    component:
    - name: clair
      managed: true
    - name: horizontalpodautoscaler
      managed: true
    - name: mirror
      managed: true
    - name: monitoring
      managed: false
    - name: postgres
      managed: true
    - name: redis
      managed: true
    - name: objectstorage
      managed: true
    - name: route
      managed: true
    - name: tls
      managed: true
    - name: quay
      managed: true
    - name: clairpostgres
      managed: true
    configBundleSecret:
      deploy: true
      name: quay-config-bundle-secret
    param:
      # Create superuser
      FEATURE_USER_INITIALIZE: true
      SERVER_HOSTNAME: quay1.apps.umrtestrocp.tim.tr
      SETUP_COMPLETE: true
      SUPER_USERS:
      - quayadmin
      FEATURE_USER_CREATION: true
      #Allow api calls 
      BROWSER_API_CALLS_XHR_ONLY: false  
      ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
      DEFAULT_TAG_EXPIRATION: 2w
      ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg
      FEATURE_BUILD_SUPPORT: false
      FEATURE_DIRECT_LOGIN: true
      FEATURE_MAILING: false
      # Enabling New functionality in Quay 3.12
      FEATURE_UI_V2: true
      FEATURE_UI_V2_REPO_SETTINGS: true
      FEATURE_AUTO_PRUNE: true
      ROBOTS_DISALLOW: false
      FEATURE_REPO_MIRROR: true
      REPO_MIRROR_INTERVAL: 30
      REPO_MIRROR_SERVER_HOSTNAME: quay1.apps.umrtestrocp.tim.tr
      REPO_MIRROR_TLS_VERIFY: false
      REPO_MIRROR_ROLLBACK: true 
      PERMANENTLY_DELETE_TAGS: true
      ESET_CHILD_MANIFEST_EXPIRATION: true
      REGISTRY_TITLE: Red Hat Quay
      REGISTRY_TITLE_SHORT: Red Hat Quay
      TAG_EXPIRATION_OPTIONS:
      - 2w
      #SSL/TLS
      SERVER_HOSTNAME: quay1.apps.umrtestrocp.tim.tr
      #EXTERNAL_TLS_TERMINATION: false
      #PREFERRED_URL_SCHEME: https
      TESTING: false  
      FEATURE_SUPERUSERS_FULL_ACCESS: true
