idm_users:
  - name: admin
    givenname: admin
    sn: admin
    password: 'redhat123'
    state: present

idm_system_users:
  - name: ocp-bind-user
    givenname: OpenShift
    sn: User
    password: 'OpenShift.2023'
    state: present
  - name: osp-bind-user
    givenname: OpenStack
    sn: User
    password: '8EGQSpjIm5UtFeLzyRM/nQ=='
    state: present
  - name: quay-bind-user
    givenname: Quay
    sn: User
    password: 'vriESYGoV02AIsXoCZjhdw==' # openssl rand -base64 16
    state: present
  - name: quay
    givenname: Quay
    sn: Reg
    password: 'registry' # openssl rand -base64 16
    state: present
  - name: ansible-bind-user
    givenname: Ansible
    sn: User
    password: 'Jn6E7Mpsi9fb07cJzEwbJw==' # openssl rand -base64 16
    state: present
  - name: satellite-bind-user
    givenname: Satellite
    sn: User
    password: '3dKSPe4Q3WG5e5MDdO4RDw==' # openssl rand -base64 16
    state: present
  - name: coreos-bind-user
    givenname: Coreos
    sn: user
    password: 'redhat123'
    state: present    

idm_groups:
  - cicd-admins
  - cnf-devs
  - gitlab-cicd
  - grp-openstack
  - ocpusers
  - ocpadmins
  - quayusers
  - ansibleusers
  - rhcosadmins

ocp_admin_users:
  - admin
  - rhcos_admin_users:
  - admin
