apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
  labels:
    stf: true
  name: stf-monitoring-stack
  namespace: service-telemetry
spec:
  logLevel: debug
  namespaceSelector:
  retention: 1d
  resourceSelector:
    matchLabels:
      app: smart-gateway
  prometheusConfig:
    replicas: 1
    externalLabels:
      prometheus: service-telemetry/default
      prometheus_replica: prometheus-default-0
    remoteWrite:
      - url: http://stf-kafka-adapter-svc.prom-kafka-adapter.svc.cluster.local:8080/receive
    persistentVolumeClaim:
      storageClassName: ocs-storagecluster-ceph-rbd
      resources:
        requests:
          storage: 20G
