apiVersion: v1
kind: Service
metadata:
  name: stf-kafka-adapter-svc
  namespace: {{ .Values.prom_kafka.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  labels:
    app: stf-prometheus-kafka-adapter
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: stf-prometheus-kafka-adapter

