apiVersion: v1
kind: ServiceAccount
metadata:
  name: stf-admin-sa
  namespace: {{ .Values.stf.namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"

