global:
  xraylab:
    namespace: "openshift-storage"
  datacenter:
    storageClassName: gp2
    region: tr-gbz-1

odf:
  jobTerminationGracePeriod: 300
  namespace: openshift-storage
  storageClass:
    name: ocs-storagecluster-ceph-rbd
    objectStoreName: ocs-storagecluster-cephobjectstore

toolbox:
  name: ocsinit
  enableCephTools: true

#Define the odf storageSystem parameters
storageSystem:
  deploy: true
  name: ocs-storagecluster-storagesystem
  namespace: openshift-storage
  spec:
    kind: storagecluster.ocs.openshift.io/v1
    name: ocs-storagecluster
    namespace: ""

#RoleBasedAccessControl
serviceAccountName: odf-node-label-sa
rbac:
  roles:
    - name: odf-label-storage-nodes
      createRole: true
      apiGroups:
        - '""'
      scope:
        cluster: true
      resources:
        - nodes
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
    - name: odf-edit-storageclass
      createRole: true
      apiGroups:
        - 'storage.k8s.io'
      scope:
        cluster: true
      resources:
        - storageclasses 
      resourceNames:
        - ocs-storagecluster-ceph-rbd
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
  roleBindings:
    - name: odf-label-storage-nodes
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: odf-node-label-sa
        namespace: openshift-storage
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: odf-label-storage-nodes
    - name: odf-edit-storageclass
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: odf-node-label-sa
        namespace: openshift-storage
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: odf-edit-storageclass

