apiVersion: metal3.io/v1alpha1
kind: Provisioning
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: provisioning-configuration
spec:
  watchAllNamespaces: true  #enable watch all ns

